use udh;

SELECT * FROM ESTUDIANTES;

INSERT INTO ESTUDIANTES(CODIGO, NOMBRES, APELLIDOS, TELEFONO, CORREO, ID_PA) VALUES('2017110754','Manuel','Cruz','954622077','manuel98_23@outlook.es','1');

INSERT INTO ESTUDIANTES(CODIGO, NOMBRES, APELLIDOS) VALUES('98765498','Piero','Sanchez');

DELETE FROM ESTUDIANTES WHERE ID=29;

UPDATE ESTUDIANTES SET NOMBRES='Manuel' WHERE ID=28;

UPDATE ESTUDIANTES SET NOMBRES='Ricardo' WHERE ID=10;

SELECT ES.CODIGO, ES.NOMBRES, ES.APELLIDOS, PA.NOMBRE FROM ESTUDIANTES AS ES JOIN PA AS PA ON ES.ID_PA=PA.ID